id: PF7B707AB
initial_creation_type: input
source_metadata:
  title: Works of Lama Dampa Sönam Gyaltsen
  parent: 2. Collected works
  source: https://sakyalibrary.com
  bases:
    26fe:
      title: སྨོན་པ་བྱང་ཆུབ་མཆོག་ཏུ་སེམས་བསྐྱེད་པ་ཐེག་ཆེན་ལམ་གྱི་སྙིང་པོའོ།།
      author: བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན།
      base_file: 26fe.txt
      order: 1
    7f30:
      title: བྱང་ཆུབ་ཀྱི་སྤྱོད་པ་ལ་འཇུག་པའི་རྣམ་པར་བཤད་པ་དགོངས་པ་ངེས་པར་གསལ་བ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན།
      base_file: 7f30.txt
      order: 2
    e4e4:
      title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་བསྡུས་དོན་བཞུགས་སོ།།
      author: བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན།
      base_file: e4e4.txt
      order: 3
    b039:
      title: བྱང་ཆུབ་སེམས་དཔའི་སྡོམ་པའི་ཆོ་ག་དགེ་ལེགས་ཀྱི་ཆུ་རྒྱུན་ནོ།།
      author: བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན།
      base_file: b039.txt
      order: 4
    c6ca:
      title: སེམས་བསྐྱེད་པའི་ཆོ་ག་མདོ་ཙམ་དུ་བྱས་པ།།
      author: བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན།
      base_file: c6ca.txt
      order: 5
    098e:
      title: ཆོས་རྗེ་བླ་མ་དམ་པས་ཏ་དབེན་པའི་ཞུ་ལན་དུ་མཛད་པ་བཞུགས་སོ།།
      author: བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན།
      base_file: 098e.txt
      order: 6
    f51f:
      title: ཡར་ལུངས་སྣེ་གདོང་དུ་གུ་ཤྲཱི་ཆེན་པོའི་ཆོས་འཁོར་དུས་ཀྱི་བསྟན་རྩིས་བཞུགས་སོ།།
        ནང་གསེས་ཞུས་ལན་དང་། སྤྲིངས་ཡིག་སོགས་ཡོད།
      author: བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན།
      base_file: f51f.txt
      order: 7
    4b52:
      title: ཚད་མ་རྣམ་འགྲེལ་གྱི་འགྲེལ་པ་ལེགས་པར་བཤད་པའི་སྙིང་པོ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན།
      base_file: 4b52.txt
      order: 8
    a1f4:
      title: བསྡུས་པ་ཆེ་བ་རིགས་པའི་དེ་ཉིད་རྣམ་པར་ངེས་པ་བཞུགས་སོ།།
      author: བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན།
      base_file: a1f4.txt
      order: 9
    7d4e:
      title: སྡེ་བདུན་གྱི་སྙིང་པོ་རིགས་པའི་དེ་ཁོ་ན་ཉིད་རབ་ཏུ་གསལ་བ་ཞེས་བྱ་བ་བསྡུས་པ་གཉིས་པ་བཞུགས་སོ།།
      author: བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན།
      base_file: 7d4e.txt
      order: 10
created_at: '2022-04-06T16:29:02.034884'
last_modified_at: '2022-04-06T16:29:02.034891'
